const descripcion = document.getElementById("descripcion")
const compra = document.getElementById("compra")
const venta = document.getElementById("venta")
const basico = document.getElementById("basico")
const minimo = document.getElementById("minimo")
const exento = document.getElementById("exento")
const subtotal = document.getElementById("subtotal")
const boton = document.getElementById("button")
const totalventas = 
const totalcompras =
const textofinal = "Total Ventas: $" + totalventas + "Total Compras: $" + totalcompras